.npmignore, ci/templates/publish.yml, package.json
- Add .npmignore
- Improve publish script
- version 1.0.5
=> Improve NPM publishing

ci/templates/publish.yml, package-lock.json
- fix npm deploy
- Actualize 'package-lock.json'
=> Npm publishing fix

src/index.ts, src/reports/index.ts, src/sourceFiles/index.ts, src/translationStatus/index.ts, src/translations/index.ts, src/users/index.ts, src/vendors/index.ts, src/workflows/index.ts, tests/reports/api.test.ts, tests/sourceFiles/api.test.ts, tests/translationStatus/api.test.ts, tests/translations/api.test.ts, tests/users/api.test.ts, tests/vendors/api.test.ts, tests/workflows/api.test.ts
=> feat: implemented Vendors, Users, Workflows APIs and updates in exiting

CHANGELOG.md, package-lock.json, package.json, src/core/index.ts, src/dictionaries/index.ts, src/index.ts, src/labels/index.ts, src/projectsGroups/index.ts, src/sourceFiles/index.ts, src/sourceStrings/index.ts, src/stringTranslations/index.ts, src/tasks/index.ts, src/translations/index.ts, src/users/index.ts, tests/dictionaries/api.test.ts, tests/labels/api.test.ts, tests/users/api.test.ts
New:
- Labels API
- Dictionaries API
Updates:
- Projects API
- Files API
- Strings API
- String Translations API
- Tasks API
- Translations API
- Users API
=> WIP Api updates

CHANGELOG.md, package-lock.json, package.json, src/glossaries/index.ts, src/index.ts, src/issues/index.ts, src/stringComments/index.ts, tests/stringComments/api.test.ts
* added new parameters to glossaries.listTerms method
* added String Comments API
* marked Issues API as deprecated
=> API updates

CHANGELOG.md, package-lock.json, package.json, src/reports/index.ts, tests/reports/api.test.ts
* updated existing methods
* added extra methods for Enterprise API
=> Report API updates

package-lock.json, package.json
=> Version increment

package-lock.json, package.json, src/users/index.ts, tests/users/api.test.ts
* invite user
* delete user
* edit user
=> Users API updates

src/languages/index.ts
Fixes https://github.com/crowdin/crowdin-api-client-js/issues/179
=> Fix LanguagesModel dialectOf type

.github/dependabot.yml
Added Dependabot configuration to automatically check for updates on packages on a weekly basis. It will also create a PR whenever there is an update.
Link to issue this resolves
Fixes: https://github.com/crowdin/crowdin-api-client-js/issues/192
=> Created Dependabot.yml

package-lock.json, package.json, src/screenshots/index.ts
=> Screenshots API updates

.github/workflows/basic.yml, .github/workflows/docs.yml
- stop using Node 14, add Node 18
- do not run lint in the matrix
- do not report tests for dependabot branches
- update some actions' versions
- minor refactoring and cleanup
=> ci: refactor workflows

src/projectsGroups/index.ts
updated interface with an optional templateId
=> made templateId optional

EXAMPLES.md, README.md, src/reports/index.ts, tests/reports/api.test.ts
=> docs: Examples

.github/workflows/publish.yml
https://github.blog/2023-04-19-introducing-npm-package-provenance/
=> ci: configure npm provenance for package publishing

package-lock.json, package.json, src/tasks/index.ts, src/translationStatus/index.ts
* Task API updates #280 
* Translation Status API updates #279
=> feat: API updates

src/applications/index.ts, src/index.ts, tests/applications/api.test.ts
Hi @andrii-bodnar, this merge adds support for Applications APIs as mentioned in #309.
=> feat: Applications Api Support

README.md, src/stringTranslations/index.ts
Added new parameters support: labelIds, excludeLabelIds to List Translation Approvals and List Translation Votes.
Fixes: #316
=> feat: Added api params to string translation approvals and votes API

src/applications/index.ts, tests/applications/api.test.ts
Hi @andrii-bodnar, this merge adds support for new Application API endpoints as mentioned in #346.
=> feat: support for new endpoints

src/webhooks/index.ts
=> fix: webhook event - source string change trigger

src/stringTranslations/index.ts, tests/stringTranslations/api.test.ts
Added support for the new 'Remove String Approvals' API endpoint.
This PR references issue #433.
=> feat: Remove String Approvals

src/core/index.ts, src/teams/index.ts, src/users/index.ts
=> feat: Teams and Users API: support more parameters (#482)

src/distributions/index.ts
=> feat: Distributions API: add support for the manifestUrl field (#462)

README.md
https://github.com/orgs/community/discussions/141424
=> docs: remove the runkit link
