crowdin/crowdin-api-client-js

src/translations/index.ts
tests/translations/api.test.ts

translationsApi.uploadTranslations was failing due to invalid type of storageId
Here is the error response: 
{"errors":[{"error":{"key":"storageId","errors":[{"code":"intTypeInvalid","message":"Invalid type given. Int expected"}]}}]}

changed UploadTranslationRequest.storageId type to number

---

src/core/internal/axios/axiosProvider.ts
src/translations/index.ts

I was looking at using https://support.crowdin.com/api/v2/#operation/api.projects.translations.builds.files.post, and noticed that there wasn't a way to set the etag header parameter, and that the etag property on the response was missing. 
A few things I wasn't certain about right away:
* When testing the change I got a 500 error back:
```
{ error:
{ code: '500',
message: 'Request failed. Error: Request failed with status code 304' } }
```
The `error.response` was missing a data field so it was falling back to the `defaultError`. I made that propagate `error.response.status` as the `error.code` if it exists so it would return the right error, but I can revert / change that if you don't want that behavior
* I didn't see any instances of extending an interface in the codebase; happy to …

add 'If-None-Match' eTag param to Translations.buildProjectFileTranslation

---

src/translationStatus/index.ts
tests/translationStatus/api.test.ts

The `fileId` returned in the response for `getLanguageProgress` is currently listed as a string, but the value you get from https://support.crowdin.com/api/v2/#operation/api.projects.languages.files.progress.getMany is a number

correct type for TranslationStatusModel.FileProgress.fileId (string->number)

---

package.json
src/sourceFiles/index.ts

Set `filter` query parameter for `GET projects/{projectId}/files`.

Allow to filter files when listing

---

src/dictionaries/index.ts
src/distributions/index.ts
src/glossaries/index.ts
src/issues/index.ts
src/labels/index.ts
src/languages/index.ts
src/machineTranslation/index.ts
src/projectsGroups/index.ts
src/reports/index.ts
src/screenshots/index.ts
src/sourceFiles/index.ts
src/sourceStrings/index.ts
src/stringComments/index.ts
src/stringTranslations/index.ts
src/tasks/index.ts
src/teams/index.ts
src/translationMemory/index.ts
src/translationStatus/index.ts
src/translations/index.ts
src/uploadStorage/index.ts
src/users/index.ts
src/vendors/index.ts
src/webhooks/index.ts
src/workflows/index.ts

This PR adds links to the API documentation on Crowdin's website for all methods. I have also reordered some methods to match the documentation order

docs: add API links to all methods

---

src/workflows/index.ts
tests/workflows/api.test.ts

This PR adds two missing methods from the Crowdin Enterprise API to the workflows API. Ideally this should be merged after #148 as it integrates the features added in that PR as well

feat(Workflows): add workflow steps methods

---

ci/basic.yml
ci/templates/jobs.yml
package.json
src/core/index.ts
src/core/internal/axios/axiosProvider.ts
src/core/internal/fetch/fetchClient.ts
src/translations/index.ts
src/uploadStorage/index.ts
tsconfig.json

This PR updates CI to run on node versions 12, 14 and 16 (all the ones supported by node) and refactors some code to use the latest features from es2021. This doesn't need a release, it's a simple QOL update

chore: drop support for node 10 and use latest node 16 features

---

src/core/index.ts
src/core/internal/axios/axiosProvider.ts
src/core/internal/fetch/fetchClient.ts
src/core/internal/retry/index.ts
src/glossaries/index.ts
src/reports/index.ts
src/teams/index.ts
src/users/index.ts
src/webhooks/index.ts

I noticed there were a lot of `any` types scattered around the library so I replaced them with what I think they should actually be and added TODO comments to fix the ones I didn't as they would require a semver: major change. If you're in doubt about any of the changes let me know and I can explain the reasoning behind them!

types: improve types by reducing the use of `any`

---

src/core/index.ts
src/core/internal/axios/axiosProvider.ts

This PR simply fixes a typo in the name of the class "AxiosProvider". This can be considered non-breaking and thus semver: patch as the class is only used in private properties and not exported. This, however, doesn't need a release since it's such a minor change

fix(AxiosProvider): fix typo in name

---

src/sourceStrings/index.ts

Identifier should be optional:
But is marked as required in TypeScript
Make the field optional

fix: optionalize identifier

---

.eslintrc
src/core/index.ts
src/dictionaries/index.ts
src/distributions/index.ts
src/glossaries/index.ts
src/issues/index.ts
src/labels/index.ts
src/languages/index.ts
src/machineTranslation/index.ts
src/projectsGroups/index.ts
src/screenshots/index.ts
src/sourceFiles/index.ts
src/sourceStrings/index.ts
src/stringComments/index.ts
src/stringTranslations/index.ts
src/tasks/index.ts
src/teams/index.ts
src/translationMemory/index.ts
src/translationStatus/index.ts
src/translations/index.ts
src/uploadStorage/index.ts
src/users/index.ts
src/vendors/index.ts
src/webhooks/index.ts
src/workflows/index.ts

So it turns out that #150 introduced a bug where if you left out optional parameters you'd get a deprecation warning. This PR fixes it by checking if the argument was passed to the function and only emits the warning if so. The solution isn't ideal but it's the best thing I found so please let me know if you have better ideas

fix: don't emit deprecation warn when argument is absent

---

package-lock.json
package.json
src/core/index.ts
src/core/internal/axios/axiosProvider.ts

Improved error handling to throw `Error` instances

Error handling improvements

---

src/uploadStorage/index.ts
tests/uploadStorage/api.test.ts

Encoded the Crowdin-API-FileName header value according to the [documentation](https://developer.crowdin.com/api/v2/#operation/api.storages.post).
Also added a test case to test the method that encoded the value.

#188 - Encode the Crowdin-API-FileName

---

package-lock.json
package.json
src/uploadStorage/index.ts

Fix for `addStorage` to pass file content as string
```js
const contentString = fs.readFileSync(file, 'utf8');
const contentBuffer = fs.readFileSync(file);
//both options now will produce file with correct type
await client.uploadStorageApi.addStorage(file, contentBuffer);
//or
await client.uploadStorageApi.addStorage(file, contentString);
```

Fix: storage upload for string

---

src/translations/index.ts
tests/translations/api.test.ts

The new labelIds and excludeLabelIds parameters have been added to the "Apply Pre-Translation" method in this API client.
- Updated PreTranslateRequest interface
- Updated PreTranslationStatusAttributes interface
- Created new test case for labelIds & excludedLabelIds
API Reference:
[Apply Pre-Translation](https://developer.crowdin.com/enterprise/api/v2/#operation/api.projects.pre-translations.post)
[Pre-Translation Status](https://developer.crowdin.com/enterprise/api/v2/#tag/Translations/paths/~1projects~1%7BprojectId%7D~1pre-translations~1%7BpreTranslationId%7D/get) (The attributes field now contains them as well)
Issue: #302

feat: Apply Pre-Translation API: add labels support

---

src/reports/index.ts
tests/reports/api.test.ts

Fixes #310 
- Added the `isPublic` property to the ReportSettings Interface
- Updated the Reports API test to include the `isPublic` property in the ReportSettings interface
Completed Pull Request Checklist
<details>
<summary><strong>Click here</strong> to see my <strong>failing</strong> test screenshot</summary>
<br>
<p>Here is a screenshot of my failed test after adding the <i>isPublic</i> property to the <strong>ReportSettings</strong> interface</p>
</details>
<details>
<summary><strong>Click here</strong> to see my <strong>passing</strong> tests screenshot</summary>
<br>
<p>Here is a screenshot of my passing test after adding the <i>isPublic</i> property to the <strong>ReportSettings</strong> test</p>
</details>
<details>
<summary><strong>Click here</strong> to see <i>isPublic</i> …

feat: Add isPublic property to ReportSettings

---

README.md

Readme.md Crowdin logo image not loading on coming back after viewing any file. Similar issue in another repo https://github.com/crowdin/crowdin-api-client-php/issues/164

fix: Readme.md image not loading issue.

---

src/sourceFiles/index.ts

The `Directory` interface is missing the `path` property.

fix: add missing field "path" to Directory type

---

src/core/index.ts

fix: sourceStringsApi.stringBatchOperations throws internal error inside handleHttpClientError

---

src/core/index.ts
tests/core/error-handling.test.ts

When `sourceStringsApi.stringBatchOperations` is called with payload errors, the error message has no information about the actual errors.
Print full error message
**Before:**
**After:**
Fixes: https://github.com/crowdin/crowdin-api-client-js/issues/318

fix: print full error message for stringBatchOperations errors

---

src/tasks/index.ts

The `TasksModel` types don't match the api requirements for the Add Task endpoint
- create `VendorType` (2, 3) and ensure the `type` param matches the requirements for each `CreateTask` type
- create `RequestStatus` to disallow `done` and `closed` statuses for new tasks
- add missing param `excludeLabelIds`
- add missing param `splitContent` to `CreateTaskRequest`
- fix `vendor` and `expertise ` types for `CreateTaskVendorGengoRequest` and `CreateTaskVendorTranslatedRequest`
- add missing union value `"Business"` to `Purpose` type
- create `CreateTaskBase` to hold common params for all task types
```ts
interface CreateTaskBase {
title: string;
languageId: string;
fileIds: number[];
status?: RequestStatus;
description?: string;
labelIds?: number[];
excludeLabelIds?: number[];
dateFrom?: …
```

fix: update TaskModel types

---

src/applications/index.ts
src/bundles/index.ts
src/clients/index.ts
src/distributions/index.ts
src/glossaries/index.ts
src/index.ts
src/labels/index.ts
src/machineTranslation/index.ts
src/notifications/index.ts
src/organizationWebhooks/index.ts
src/projectsGroups/index.ts
src/reports/index.ts
src/sourceStrings/index.ts
src/stringTranslations/index.ts
src/tasks/index.ts
src/teams/index.ts
src/translationMemory/index.ts
src/translationStatus/index.ts
src/translations/index.ts
src/users/index.ts
src/vendors/index.ts
src/webhooks/index.ts
tests/bundles/api.test.ts
tests/clients/api.test.ts
tests/machineTranslation/api.test.ts
tests/sourceStrings/api.test.ts
tests/stringTranslations/api.test.ts
tests/translationMemory/api.test.ts
tests/translations/api.test.ts
tests/users/api.test.ts

Added new & updated existing methods to support Strings-based projects

feat: Strings based API methods

---

src/core/index.ts
tests/core/error-handling.test.ts

There is no useful information in the error message when task creation fails due to a vendor issue
Print full error message
**Before:**
**After:**

fix: update error message for task creation errors

---

src/core/index.ts
src/translationMemory/index.ts

Allow graphql for crowdin.com, add croql to listTmSegments

feat: allow graphql for crowdin.com, add croql to listTmSegments

---

src/fields/index.ts
src/index.ts
tests/fields/api.test.ts

Add support for fields API https://developer.crowdin.com/enterprise/api/v2/#tag/Fields

feat: add fields API support

---

src/translations/index.ts
tests/translations/api.test.ts

feat: add support for the new Pre-Translation API endpoint

---

src/screenshots/index.ts

This PR fixes a bug where the `stringIds` parameter was defined in the `ListScreenshotParams` interface but was not being passed to the API request.
- Added missing `stringIds` query parameter handling in `listScreenshots` method
- The parameter was already defined in the interface but not implemented in the URL construction
The `stringIds` option was available in the TypeScript interface but wasn't being sent to the Crowdin API, causing the filtering to not work as expected.
- Crowdin API documentation: [List Screenshots](https://developer.crowdin.com/api/v2/#operation/api.projects.screenshots.getMany)

fix(screenshots): add missing stringIds query parameter to listScreenshots
